### ISSUE TITLE
界面适配

### ISSUE THREAD

**Issue by xiaohaoWit** [lzjin/AlipayPassDialog#2]
你的界面适配没做好，键盘的 一加6T显示键盘中间有空隙

**Comment by xiaohaoWit** [comment]
<Button
            android:id="@+id/btNumber"
            android:layout_width="120dp"
            android:layout_height="55dp"
            android:textSize="@dimen/sp_26"
            android:textColor="@color/black"
            android:background="@drawable/payview_btn_selector"/>

这个地方的宽度不对  应该是match_parent  或者是设置  android:layout_width="0dp" android:layout_weight="3"  

请有时间更新下

**Comment by xiaohaoWit** [comment]
```
 <Button
            android:id="@+id/btNumber"
            android:layout_width="0dp"
            android:layout_weight="3"
            android:layout_height="55dp"
            android:textSize="@dimen/sp_26"
            android:textColor="@color/black"
            android:background="@drawable/payview_btn_selector"/>
```

这个地方的宽度不对 应该是match_parent 或者是设置 android:layout_width="0dp" android:layout_weight="3"

请有时间更新下

**Comment by lzjin** [comment]
界面适配已优化
